### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Blastish** [jondavid23/Mini-project-ROB5#1]
Include software and hardware. Only around half a page

**Comment by jondavid23** [comment]
This will never be completed!! MUhahaha

**Comment by LarsGS** [comment]
Hi guys

**Comment by LarsGS** [comment]
Stop scrolling

**Comment by LarsGS** [comment]
Wanna pet some cat girls?

**Comment by Blastish** [comment]
Done. Closing.
